In [1]:
import numpy as np

In [42]:
# Rank 2 tensor
arr1 = np.arange(2 * 2).reshape(2, 2)
arr2 = np.arange(4, 8).reshape(2, 2)

arr1 @ arr2

array([[ 6,  7],
       [26, 31]])

In [44]:
arr1[0, :] @ arr2[:, :]

array([6, 7])

array([2., 2.])

In [48]:
A = np.arange(2 * 2 * 2).reshape(2, 2, 2)
B = np.arange(2 * 2 * 2, 2**3 + 2**3).reshape(2, 2, 2)

In [49]:
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
B

array([[[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [51]:
A @ B

array([[[ 10,  11],
        [ 46,  51]],

       [[118, 127],
        [170, 183]]])

In [52]:
# For a rank 3 tensor, the matmul indexes over the last dimension
A[0, :, :] @ B[0, :, :]

array([[10, 11],
       [46, 51]])

In [53]:
A[1, :, :] @ B[1, :, :]

array([[118, 127],
       [170, 183]])

In [76]:
# Rank 4 tensor
A = np.arange(3**3 * 2).reshape(3, 2, 3, 3)
B = np.arange(3**3 * 2, 3**3 * 2 + 3**3 * 2).reshape(2, 3, 3, 3)

out = A @ B
print(out.shape)
out

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2,3,3)->(3,2,newaxis,newaxis) (2,3,3,3)->(2,3,newaxis,newaxis)  and requested shape (3,3)

In [58]:
A[0, 0, :, :] @ B[0, 0, :, :]

array([[18, 19],
       [86, 91]])

In [59]:
A[0, 1, :, :] @ B[0, 1, :, :]

array([[190, 199],
       [274, 287]])

In [60]:
A[1, 0, :, :] @ B[1, 0, :, :]

array([[426, 443],
       [526, 547]])

In [61]:
A[1, 1, :, :] @ B[1, 1, :, :]

array([[726, 751],
       [842, 871]])

In [ ]:
# General matmul algorithm for an ndarray
# We fix the last two indices which we can think of as our clump of 2D matrices
# We index over the first n-2 indices, starting with the n - 2, then n - 3 and so on
def matmul(a, b, stride_a, stride_b):
    """
    i = # of rows of a
    j = # of cols of a / # of rows of b
    k = # or cols of b
    """
    for i in range(stride_a[0]):
        for j in range(stride_a[0]):
            for k in range(stride_b[1]):
                

In [146]:
def iterate_nd(dims):
    inds = [0] * len(dims)
    cur_dim = len(dims) - 3

    i = len(dims) - 3
    while (cur_dim >= 0):
        while i != cur_dim:
            while inds[i] != dims[i] - 1:
                print(inds, i, cur_dim, 'a')
                inds[i] += 1
                
            print(inds, i, cur_dim, 'b')
            inds[i] = 0
            i -= 1
        
        if inds[cur_dim] == dims[cur_dim] - 1:
            inds[cur_dim] = 0
            cur_dim -= 1
            inds[cur_dim] += 1
        else:
            inds[cur_dim] += 1
            
        print(inds, i, cur_dim, 'u')
        
        i = len(dims) - 3
        
            
iterate_nd([4, 4, 4, 4, 4])

[0, 0, 1, 0, 0] 2 2 u
[0, 0, 2, 0, 0] 2 2 u
[0, 0, 3, 0, 0] 2 2 u
[0, 1, 0, 0, 0] 2 1 u
[0, 1, 0, 0, 0] 2 1 a
[0, 1, 1, 0, 0] 2 1 a
[0, 1, 2, 0, 0] 2 1 a
[0, 1, 3, 0, 0] 2 1 b
[0, 2, 0, 0, 0] 1 1 u
[0, 2, 0, 0, 0] 2 1 a
[0, 2, 1, 0, 0] 2 1 a
[0, 2, 2, 0, 0] 2 1 a
[0, 2, 3, 0, 0] 2 1 b
[0, 3, 0, 0, 0] 1 1 u
[0, 3, 0, 0, 0] 2 1 a
[0, 3, 1, 0, 0] 2 1 a
[0, 3, 2, 0, 0] 2 1 a
[0, 3, 3, 0, 0] 2 1 b
[1, 0, 0, 0, 0] 1 0 u
[1, 0, 0, 0, 0] 2 0 a
[1, 0, 1, 0, 0] 2 0 a
[1, 0, 2, 0, 0] 2 0 a
[1, 0, 3, 0, 0] 2 0 b
[1, 0, 0, 0, 0] 1 0 a
[1, 1, 0, 0, 0] 1 0 a
[1, 2, 0, 0, 0] 1 0 a
[1, 3, 0, 0, 0] 1 0 b
[2, 0, 0, 0, 0] 0 0 u
[2, 0, 0, 0, 0] 2 0 a
[2, 0, 1, 0, 0] 2 0 a
[2, 0, 2, 0, 0] 2 0 a
[2, 0, 3, 0, 0] 2 0 b
[2, 0, 0, 0, 0] 1 0 a
[2, 1, 0, 0, 0] 1 0 a
[2, 2, 0, 0, 0] 1 0 a
[2, 3, 0, 0, 0] 1 0 b
[3, 0, 0, 0, 0] 0 0 u
[3, 0, 0, 0, 0] 2 0 a
[3, 0, 1, 0, 0] 2 0 a
[3, 0, 2, 0, 0] 2 0 a
[3, 0, 3, 0, 0] 2 0 b
[3, 0, 0, 0, 0] 1 0 a
[3, 1, 0, 0, 0] 1 0 a
[3, 2, 0, 0, 0] 1 0 a
[3, 3, 0, 0, 0] 1 0 b
[0, 0, 0, 

In [ ]:
            if (inds[cur_dim] == dims[cur_dim] - 1):
                cur_dim -= 1
                inds[cur_dim] += 1
                inds[i] = 0
            elif (inds[i] == dims[i] - 1):
                inds[cur_dim] += 1
                inds[i] = 0
            else:
                inds[i] += 1